extends "res://story/ch5/common.gd"
## 5장 대본 — 1. 축제 — 시작·축제 광장·사진·저녁(리라 방문).
## 메서드 이름 = 실행 ID (docs/dev/story.md). 장 공용 상수·도우미는 common.gd.


# ═══════════════════════════════════════════════════════════
# 1. 축제 (학교)
# ═══════════════════════════════════════════════════════════

## 4장 끝 → 장 카드 → 여기 (검은 화면, HUD 꺼짐)
func ch5_start(c: Cut) -> void:
	c.lock()
	c.flag("st_fest")
	c.hud(true)
	c.music("festival", 2.0)
	await c.goto_room("s_courtyard", "gate")
	c.lock()
	await c.fade_out(0.01)
	c.player_face(1)
	c.letterbox(true)
	await c.wait(0.4)
	await c.fade_in(1.0)
	await c.title_card("축제의 날", "신전에서 돌아온 다음 날 — 마녀학교", 2.4)
	c.spawn_npc("pippa", 52.0, 19.0, -1)
	await c.walk("pippa", 44.0, 120.0)
	await c.say("pippa", "세라—! 찾았다! 오늘 무슨 날인지 알지? 축! 제!", "happy")
	await c.say("sera", "…알아. 어젯밤에 신전에서 돌아왔잖아. 아직 다리가 후들거려.")
	await c.say("pippa", "그러니까 더 놀아야지! 내 물약 가게 꼭 와. 오늘만 파는 '별사탕 물약'도 있어!", "happy")
	c.bubble("별사탕… 먹을 수 있는 것이니라?", 2.2)
	await c.say("pippa", "광장은 앞마당 오른쪽 끝이야. 레오니 단장님이랑 엘라리엔이랑 아우렐리아도 가게를 열었대! 교장 선생님이 초대하셨다나 봐.")
	await c.say("sera", "…아우렐리아가 가게를? 상상이 안 되는데.", "surprised")
	c.close_box()
	c.sfx("whoosh", -6.0)
	c.face("hodu", -1)
	await c.move("hodu", 46.0, 10.0, 0.01)
	await c.move("hodu", 41.0, 19.0, 0.8)
	await c.say("hodu", "호우.")
	await c.say("pippa", "어, 호두다. 그레타 선생님네 부엉이. …편지? 아, 교장 선생님께 드릴 축제 초대장이구나.")
	await c.say("pippa", "학생 대표가 전해 드리는 게 전통이거든. 그리고 올해 학생 대표는— 짜잔, 우리 세라!", "happy")
	await c.say("sera", "그런 걸 왜 마음대로 정해!", "angry")
	await c.say("pippa", "투표했어. 만장일치. …이졸데도 손 들었다?", "smug")
	await c.say("sera", "…이졸데가?", "surprised")
	c.close_box()
	await c.item("축제 초대장", "교장실(시계탑 꼭대기)의 아스트리드 교장에게 전하자.")
	await c.say("hodu", "호우. 호우우.")
	await c.say("pippa", "호두가 초대장이 아직 잔뜩 남았대. 한가하면 같이 돌려 달라는데? 그럼 난 가게 준비하러 간다!", "happy")
	c.close_box()
	c.walk("pippa", 70.0, 140.0)
	await c.wait(0.6)
	c.hide_actor("pippa")
	await c.say("neoul", "…세라. 어젯밤 첨탑 위의 그 마녀 말이다.")
	await c.say("sera", "'잘 자랐구나, 나의 별.' …나도 계속 생각나.", "sad")
	await c.say("neoul", "그 별빛, 어디선가 맡아 본 냄새였느니라. 아주 오래전에.")
	await c.say("neoul", "…허나 오늘은 축제니라. 일단 먹고, 생각은 그다음에 하자꾸나.", "happy")
	await c.say("sera", "너 그냥 배고픈 거지.", "smug")
	c.close_box()
	c.letterbox(false)
	c.save()
	c.release()


func st_yard_first(c: Cut) -> void:
	await c.wait(0.2)
	c.bubble("고소한 냄새가… 오른쪽 끝에서 나는구나.", 2.6)


func enter_st_festival(c: Cut) -> void:
	match _phase(c):
		"fest":
			if c.has("st_fest_seen"):
				return
			c.flag("st_fest_seen")
			c.lock()
			c.music("festival")
			await c.wait(0.3)
			await c.camera_to(Vector2(30 * 16.0, 15 * 16.0), 1.2)
			await c.say("leonie", "세라. 왔군.")
			await c.say("leonie", "제국 기사단이 가게를 연다. 카엘의 생각이다. …나는 굽기만 한다.")
			await c.camera_to(Vector2(42 * 16.0, 15 * 16.0), 0.8)
			await c.say("elarien", "꿀빵이다. 숲의 벌이 만든 꿀. …사람이 많군.")
			await c.camera_to(Vector2(82 * 16.0, 15 * 16.0), 1.0)
			await c.say("aurelia", "루멘 대신전의 성찬 빵입니다. 축제에 빵을 나누는 것도 신전의 일입니다.")
			await c.say("sera", "아우렐리아가… 빵을 팔아?", "surprised")
			await c.say("aurelia", "나눕니다. 팔지 않습니다.")
			await c.camera_back(0.8)
			await c.say("neoul", "…세라. 여기는… 천국이니라.", "happy")
			c.close_box()
			c.release()
			await c.teach("축제", "인물에게 말을 걸어 축제를 즐기자. 부탁(퀘스트)이 있는 인물 머리 위엔 ! 가 뜬다.\n저녁 무도회는 광장 가운데 무대에서. 그 전에 교장실에 초대장을 전하자.", ["move_up"])
		"trial":
			await c.wait(0.4)
			c.bubble("광장이 텅 비었구나… 다들 무사해야 할 텐데.", 2.6)
		"epi":
			if c.has("ch5_done") and not c.has("st_fest2_seen"):
				c.flag("st_fest2_seen")
				await c.wait(0.4)
				c.bubble("축제를 다시 열었구나. …냄새가 그대로니라!", 2.6)


## 교장실 덧붙임 트리거: 창립자의 사진
func st_photo_scene(c: Cut) -> void:
	if c.has("st_fest_ready"):
		return
	c.lock()
	await c.wait(0.4)
	c.face("astrid", -1)
	await c.say("sera", "교장 선생님. 축제 초대장 가져왔어요.")
	await c.say("astrid", "…고마워요, 세라피나 양. 올해도 학생 대표에게 받는군요.")
	await c.player_walk(10.0)
	await c.say("sera", "그 사진…")
	await c.say("astrid", "창립자이신 선생님과, 마지막 제자 둘. 백이십 년 전이에요.")
	await c.say("sera", "이 작은 쪽이 교장 선생님? …그럼 이쪽은요? 모자가 엄청 크네.", "surprised")
	await c.say("astrid", "…별을 무척 좋아하던 선배였죠.")
	await c.say("astrid", "선생님이 돌아가신 해에 '별을 보러 간다'며 떠났어요. 그 뒤로는 한 번도.", "sad")
	c.close_box()
	c.emote("neoul", "...")
	await c.say("neoul", "(…저 모자. 어젯밤 첨탑 위의 그림자도 저런 모자였느니라.)")
	await c.say("sera", "(…응. 나도 봤어.)", "sad")
	c.close_box()
	c.face("astrid", 1)
	c.emote("astrid", "...")
	await c.say("astrid", "축제는 언제나 생각보다 짧답니다. 하고 싶은 일은 저녁 무도회 전에 다 해 두세요.")
	await c.say("astrid", "불사조의 금서를 원한다면 도서관의 그레타 선생님께. 서명은 언제든 해 드리죠.")
	await c.say("astrid", "저녁에 광장 무대에서 불꽃놀이가 시작되면… 저도 내려가겠어요.", "wink")
	c.close_box()
	c.flag("st_fest_ready")
	c.save()
	c.release()


## 축제 광장 무대: 저녁 축제 시작 물음
func st_evening_ask(c: Cut) -> void:
	if c.has("st_lyra_came") or not c.has("st_fest_ready"):
		return
	var i := await c.choose("sera", "저녁 축제를 시작할까? (무도회와 불꽃놀이 — 낮의 부탁은 그 전에)", ["시작하자", "조금 더 둘러볼래"])
	c.close_box()
	if i == 0:
		await st_evening(c)


## 2. 리라의 방문 (축제 광장)
func st_evening(c: Cut) -> void:
	c.lock()
	c.hud(false)
	await c.fade_out(1.2)
	c.close_box()
	await c.narrate("해가 지고 — 축제의 저녁.")
	c.close_box()
	c.player.global_position = c.marker("evening")
	c.player_face(1)
	c.spawn_npc("astrid", 62.0, 16.0, -1)
	c.letterbox(true)
	c.music("festival")
	await c.fade_in(1.6)
	c.sfx("crowd", -4.0)
	await c.say("astrid", "여러분. 올해도 무사히 축제를 열게 되어 기쁩니다.")
	await c.say("astrid", "이 학교의 결계는 백 년 동안 한 번도 깨진 적이 없어요. 오늘 밤도 마음껏 즐기세요.", "happy")
	c.close_box()
	for i in 3:
		c.flash([Color(1.0, 0.8, 0.45, 0.25), Color(0.55, 0.8, 1.0, 0.25), Color(0.85, 0.6, 1.0, 0.25)][i], 0.4)
		c.sfx("explode", -10.0)
		await c.wait(0.5)
	c.sfx("crowd", -2.0)
	await c.say("emberlyn", "불꽃은 내 담당이다. …올해는 아무도 그을리지 않았다.", "happy")
	await c.say("isolde", "…세라. 무도회 상대가 없으면, 내가 해 줄 수도 있어. 어디까지나 할 수도 있다는 거야.")
	await c.say("sera", "응? 이졸데, 지금 얼굴 빨개진 거—", "smug")
	await c.say("isolde", "불꽃 때문이야!", "angry")
	c.close_box()
	await c.wait(0.4)
	await c.say("ophelia", "어머~ 저 별, 아까보다 더 가까워졌네~? 별이 걸어 내려오는 건… 처음 보는데~", "surprised")
	c.close_box()
	# 별이 내려온다
	Music.stop(1.0)
	await c.camera_to(Vector2(62 * 16.0, 6 * 16.0), 1.2)
	c.sfx("star_twinkle", 2.0)
	await c.wait(0.8)
	c.shake(0.15, 1.0)
	c.sfx("sky_crack", 4.0)
	c.flash(Color(1, 1, 1, 0.85), 0.6)
	c.burst(Vector2(62 * 16.0, 6 * 16.0), 80, Color(0.85, 0.9, 1.0),
		{spread = 180.0, speed_min = 80.0, speed_max = 320.0, lifetime = 1.2, size_min = 2.0, size_max = 5.0, gravity = Vector2(0, 200)})
	await c.narrate("쩌억 — 하는 소리와 함께, 학교를 백 년 동안 지켜 온 큰 결계가 유리처럼 갈라졌다.")
	c.close_box()
	c.sfx("crowd", 2.0)
	c.spawn_npc("lyra", 62.0, 3.0, -1)
	c.pose("lyra", "cast")
	c.music("lyra", 2.0)
	await c.move("lyra", 62.0, 11.0, 2.4)
	c.pose("lyra", "idle")
	await c.say("lyra", "안녕, 꼬마 아스트리드. …많이 늙었네.", "happy")
	await c.say("astrid", "선배는 하나도 안 변했군요.")
	await c.camera_back(0.8)
	await c.say("lyra", "그리고—", "normal")
	c.face("lyra", -1)
	await c.say("lyra", "잘 자랐구나, 나의 별.", "happy")
	await c.say("sera", "당신… 어젯밤 첨탑 위의.", "surprised")
	c.vignette(0.4)
	await c.say("neoul", "이 냄새… 별의 씨앗. 네 녀석이었구나.", "scary")
	c.vignette(0.0)
	await c.say("lyra", "안녕하세요, 여우신님. 꼬리가 넷이나 돌아왔네요. 다행이에요.", "happy")
	c.close_box()
	# 교장의 진짜 힘 — 그래도 진다
	c.pose("astrid", "cast")
	await c.say("astrid", "학생들은 물러나세요.")
	await c.say("astrid", "…백 년 동안 결계를 떠받치던 손이, 오랜만에 가볍군요.")
	c.close_box()
	c.sfx("star_burst", 2.0)
	c.flash(Color(0.85, 0.85, 1.0, 0.6), 0.4)
	Fx.ring(Vector2(62 * 16.0, 14 * 16.0), 10.0, 220.0, Color(0.85, 0.85, 1.0), 0.8, 4.0)
	for k in 3:
		StStrike.spawn(Vector2((54 + k * 8) * 16.0, 8 * 16.0), "pillar", Vector2(28, 220), 0.3, {"damage": 0, "style": "star", "hold": 0.4, "fade": 0.5})
		await c.wait(0.15)
	c.shake(0.3, 0.8)
	await c.say("lyra", "와아. 그거 선생님 마법이지? 하늘을 셋으로 가르던.", "surprised")
	await c.say("lyra", "그런데 아스트리드. 그 손, 떨리고 있어.", "sad")
	c.close_box()
	c.pose("lyra", "cast")
	c.sfx("parry", 2.0)
	c.flash(Color(1.0, 0.95, 0.8, 0.7), 0.3)
	await c.wait(0.3)
	c.pose("astrid", "kneel")
	c.shake(0.2, 0.5)
	await c.say("astrid", "……!", "tired")
	await c.say("sera", "교장 선생님!", "surprised")
	c.close_box()
	# 강자들이 나서지만 — 별의 무게
	await c.say("leonie", "물러서라, 별의 마녀.")
	await c.say("elarien", "…이 거리면 빗나가지 않는다.")
	await c.say("aurelia", "학생들에게서 떨어지십시오.")
	c.close_box()
	await c.say("lyra", "제국의 검, 세계수의 눈, 빛의 수호자. 다들 와 줬구나. 고마워.", "happy")
	await c.say("lyra", "…그래도 지금은, 앉아 있어 줘.", "serious")
	c.close_box()
	c.pose("lyra", "special")
	c.sfx("star_burst", 0.0)
	c.shake(0.4, 0.6)
	c.flash(Color(1.0, 0.95, 0.8, 0.5), 0.5)
	for who in ["leonie", "elarien", "aurelia", "isolde", "emberlyn"]:
		c.pose(who, "kneel")
		var p := c.actor_pos(who)
		Fx.ring(p + Vector2(0, -12), 4.0, 26.0, StArt.STAR, 0.5, 2.0)
	await c.say("leonie", "몸이… 움직이지 않는다…", "angry")
	await c.say("aurelia", "이건… 신성력이 아닙니다. 별 하나의 무게가… 그대로.", "surprised")
	c.close_box()
	c.pose("lyra", "idle")
	await c.say("lyra", "무서워하지 마. 오늘은 인사만 하러 온 거야.", "happy")
	await c.say("lyra", "네 곳에 별을 내려 두었어. 제국, 세계수, 대신전, 그리고 이 학교의 정원.")
	await c.say("lyra", "별마다 시련이 기다려. 각자의 땅에서, 각자의 강함으로.")
	c.close_box()
	c.shake(0.35, 2.4)
	c.sfx("crumble", 2.0)
	await c.narrate("학교 뒤편 하늘로 — 별빛으로 지은 탑이 솟아올랐다.")
	c.close_box()
	await c.say("lyra", "별의 열쇠 넷을 모으면 저 탑이 열려. 꼭대기에서 기다릴게.")
	await c.say("sera", "…왜 나야. 당신은 대체 뭔데!", "angry")
	await c.say("lyra", "이기면 전부 알려 줄게. 약속해.", "serious")
	await c.say("lyra", "나를 넘어 보렴, 나의 별.", "happy")
	c.close_box()
	c.pose("lyra", "special")
	c.sfx("star_burst", 2.0)
	c.flash(Color(1.0, 0.98, 0.9, 0.8), 0.6)
	c.burst(Vector2(62 * 16.0, 10 * 16.0), 60, StArt.STAR, {spread = 180.0, speed_min = 60.0, speed_max = 260.0, lifetime = 1.0})
	c.hide_actor("lyra")
	Music.stop(2.0)
	for who in ["leonie", "elarien", "aurelia", "isolde", "emberlyn"]:
		c.pose(who, "idle")
	await c.wait(1.0)
	await c.approach("astrid", 1.5, 70.0)
	await c.say("sera", "교장 선생님! 괜찮아요?", "sad")
	await c.say("astrid", "…괜찮아요. 백 년 만에 진심으로 마법을 써 봤더니, 몸이 놀랐을 뿐이에요.", "tired")
	await c.say("astrid", "그녀의 이름은 리라. 사진 속의 그 선배예요.", "sad")
	await c.say("leonie", "제국에 별이 떨어졌다면 내 자리는 거기다. 세라— 와라. 기다리겠다.")
	await c.say("elarien", "숲에도 떨어졌다. …늦지 마라.")
	await c.say("aurelia", "대신전의 종루에 별이 내렸습니다. 먼저 가겠습니다, 세라피나.")
	await c.say("emberlyn", "정원 쪽에도 별이 떨어졌다. 이졸데와 내가 함께 간다. 학교는 우리가 지킨다.")
	await c.say("isolde", "…따라오지 말라는 말은 안 했어. 오고 싶으면 와.", "smug")
	await c.say("astrid", "앞마당에 별의 문이 열렸을 거예요. 문마다 시련이 있는 곳으로 곧장 이어지죠. …선배다운 친절이에요.")
	c.close_box()
	c.flag("st_fest_seen")
	c.flag("st_fest_ready")
	c.flag("st_lyra_came")
	c.letterbox(false)
	await c.fade_out(1.0)
	c.hud(true)
	c.music("star_tower", 1.0)
	await c.goto_room("s_courtyard", "star")
	c.lock()
	await c.wait(0.4)
	await c.say("neoul", "…세라. 저 마녀의 별빛과 네 안의 불은 같은 냄새가 나느니라.")
	await c.say("sera", "알아. 그러니까 가서 물어볼 거야. 직접.", "angry")
	c.close_box()
	c.save()
	c.release()
