/* 저주 매입합니다 — 게임 데이터 (프로토타입 v0.1)
 * 모든 수치는 docs/prototype-spec.md 의 [임시] 값이다. 플레이 후 조정한다. */
(function () {
  'use strict';
  const W = (globalThis.W = globalThis.W || {});

  const GRADES = {
    common: { name: '일반', color: '#c9bfd8', rank: 0 },
    uncommon: { name: '고급', color: '#7fdcae', rank: 1 },
    rare: { name: '희귀', color: '#86b8ff', rank: 2 },
    legend: { name: '전설', color: '#ffcf5a', rank: 3 },
  };
  const GRADE_ORDER = ['common', 'uncommon', 'rare', 'legend'];

  const ELEMENTS = {
    fire: { name: '불', color: '#ff9a52' },
    ice: { name: '얼음', color: '#8fd3ff' },
    light: { name: '빛', color: '#ffe680' },
  };

  const PLAYER = {
    name: '루미',
    base: { maxHp: 60, maxMp: 20, atk: 10, def: 4 },
    perLevel: { maxHp: 12, maxMp: 4, atk: 2, def: 1 },
    startSilver: 150,
    startItems: { hp_potion: 3, herb: 1, feather: 1 },
    maxLevel: 10,
  };

  // index = 현재 레벨, 값 = 다음 레벨까지 필요한 경험치
  const EXP_CURVE = [0, 20, 45, 80, 125, 180, 245, 320, 405, 500, 99999];

  const SPELLS = {
    fire: { id: 'fire', name: '불씨', mp: 5, kind: 'attack', elem: 'fire', power: 1.4, learn: 1,
      desc: '작은 불꽃을 던진다. 25% 확률로 화상(3턴).' },
    ice: { id: 'ice', name: '얼음 가시', mp: 6, kind: 'attack', elem: 'ice', power: 1.2, learn: 2,
      desc: '얼음 가시로 찌른다. 40% 빙결. 기를 모으는 적을 반드시 끊는다.' },
    heal: { id: 'heal', name: '치유', mp: 7, kind: 'heal', learn: 3,
      desc: '최대 체력의 30%+8 만큼 회복한다.' },
    light: { id: 'light', name: '정화의 빛', mp: 10, kind: 'attack', elem: 'light', power: 1.8, learn: 5,
      desc: '저주를 태우는 빛. 그림자 방패를 깨뜨린다.' },
  };
  const SPELL_ORDER = ['fire', 'ice', 'heal', 'light'];

  // cat: potion(물약) / tool(도구) / material(재료) / quest(의뢰 물건, 판매 불가)
  const ITEMS = {
    hp_potion: { name: '체력 물약', cat: 'potion', price: 25, icon: 'potion_red',
      desc: '체력을 40 회복한다.', use: { heal: 40 }, battle: true, field: true },
    big_potion: { name: '큰 체력 물약', cat: 'potion', price: 70, icon: 'potion_big',
      desc: '체력을 100 회복한다.', use: { heal: 100 }, battle: true, field: true, unlockFloor: 3 },
    mp_potion: { name: '마력 물약', cat: 'potion', price: 35, icon: 'potion_blue',
      desc: '마력을 15 회복한다.', use: { mp: 15 }, battle: true, field: true },
    herb: { name: '해독 허브', cat: 'potion', price: 15, icon: 'herb',
      desc: '독을 치료한다.', use: { cure: 'poison' }, battle: true, field: true },
    salt: { name: '정화 소금', cat: 'material', price: 40, icon: 'salt',
      desc: '전투 중 저주를 풀어준다. 골동품 정화 재료로도 쓴다.', use: { cure: 'curse' }, battle: true, field: false },
    smoke: { name: '연막 구슬', cat: 'tool', price: 30, icon: 'smoke',
      desc: '전투에서 반드시 도망친다. 보스·의뢰 대상에게는 통하지 않는다.', use: { escape: true }, battle: true, field: false },
    feather: { name: '귀환 깃털', cat: 'tool', price: 45, icon: 'feather',
      desc: '봉인 창고에서 학교로 곧장 돌아간다.', use: { returnHome: true }, battle: false, field: true },
    firecracker: { name: '폭죽 부적', cat: 'tool', price: 40, icon: 'charm',
      desc: '적에게 불 속성 피해 30을 준다. 방어를 무시한다.', use: { damage: 30, elem: 'fire' }, battle: true, field: false },
    lamp_oil: { name: '등불 기름', cat: 'tool', price: 20, icon: 'lamp',
      desc: '이번 층에서 시야가 2칸 넓어진다.', use: { sight: 2 }, battle: false, field: true },
    key: { name: '녹슨 열쇠', cat: 'tool', price: 50, icon: 'key',
      desc: '잠긴 문이나 잠긴 상자를 연다. 쓰면 사라진다.', battle: false, field: false },
    dew: { name: '달빛 이슬', cat: 'material', price: 80, icon: 'dew',
      desc: '달빛을 머금은 이슬. 뜨거운 저주를 식히는 정화 재료.', unlockFloor: 2 },
    sand: { name: '시간의 모래', cat: 'material', price: 90, icon: 'sand',
      desc: '멈춘 시간을 다시 흐르게 하는 모래. 정화 재료.', unlockFloor: 4 },
    q_spring: { name: '잃어버린 태엽', cat: 'quest', icon: 'spring', desc: '오르골에서 빠진 작은 태엽. 가끔 찌르륵 떤다.' },
    q_strap: { name: '빗자루 끈', cat: 'quest', icon: 'strap', desc: '빗자루를 얌전하게 만드는 낡은 가죽 끈.' },
  };
  const SHOP_TABS = [
    { id: 'potion', name: '물약' },
    { id: 'tool', name: '도구' },
    { id: 'material', name: '재료' },
    { id: 'sell', name: '팔기' },
  ];

  // effect 키: atk def maxHp maxMp flee crit sight petBoost potionBoost fireBoost iceBoost lightBoost mpRegen silverBoost sleepChance trapSight
  const ANTIQUES = {
    musicbox: { name: '울지 않는 오르골', grade: 'uncommon', value: 120, icon: 'musicbox',
      effect: { maxMp: 6, sleepChance: 0.25 }, desc: '태엽을 되찾고 조용한 자장가만 부른다.' },
    handmirror: { name: '박자 맞는 손거울', grade: 'uncommon', value: 150, icon: 'mirror',
      effect: { atk: 3, flee: 0.15 }, desc: '이제 거울 속 모습이 제 박자에 움직인다.' },
    teapot: { name: '적당히 따뜻한 찻주전자', grade: 'uncommon', value: 130, icon: 'teapot',
      effect: { maxHp: 12, potionBoost: 0.3 }, desc: '언제나 마시기 좋은 온도를 지켜준다.' },
    diary: { name: '제자리 일기장', grade: 'rare', value: 200, icon: 'diary',
      effect: { maxMp: 10, fireBoost: 0.25 }, desc: '글자들이 얌전히 제 페이지에 머문다.' },
    broom: { name: '얌전한 마녀 빗자루', grade: 'rare', value: 240, icon: 'broom',
      effect: { flee: 0.3, sight: 1 }, desc: '끈을 묶자 주인 말을 잘 듣게 됐다.' },
    doll: { name: '미소 짓는 인형', grade: 'rare', value: 220, icon: 'doll',
      effect: { atk: 5, def: 2 }, desc: '깔깔대던 웃음이 잔잔한 미소가 됐다.' },
    watch: { name: '다시 흐르는 회중시계', grade: 'rare', value: 320, icon: 'watch',
      effect: { def: 3, mpRegen: 2 }, desc: '째깍째깍, 시간이 바르게 흐른다.' },
    brooch: { name: '달빛 브로치', grade: 'legend', value: 600, icon: 'brooch',
      effect: { atk: 6, maxHp: 20, maxMp: 10, lightBoost: 0.3 }, desc: '삼켰던 달빛을 돌려받아 은은하게 빛난다.' },

    cracked_mirror: { name: '금 간 손거울', grade: 'common', value: 30, icon: 'mirror2', random: true,
      effect: { atk: 2 }, desc: '금이 갔지만 아직 잘 비친다.' },
    old_candlestick: { name: '녹슨 촛대', grade: 'common', value: 30, icon: 'candle', random: true,
      effect: { sight: 1 }, desc: '불을 붙이면 유난히 멀리까지 밝힌다.' },
    faded_ribbon: { name: '빛바랜 리본', grade: 'common', value: 25, icon: 'ribbon', random: true,
      effect: { maxHp: 6 }, desc: '누군가 소중히 매던 리본.' },
    chipped_cup: { name: '이 빠진 찻잔', grade: 'common', value: 25, icon: 'cup', random: true,
      effect: { maxMp: 4 }, desc: '이 빠진 곳으로 마력이 조금씩 고인다.' },
    cat_bell: { name: '고양이 방울', grade: 'uncommon', value: 70, icon: 'bell', random: true,
      effect: { petBoost: 0.15 }, desc: '먹물이 이 소리를 들으면 힘이 난다.' },
    magnifier: { name: '할머니 돋보기', grade: 'uncommon', value: 70, icon: 'magnifier', random: true,
      effect: { trapSight: true }, desc: '숨은 함정이 희미하게 보인다.' },
    silver_thimble: { name: '은 골무', grade: 'uncommon', value: 70, icon: 'thimble', random: true,
      effect: { def: 3 }, desc: '작지만 단단하다.' },
    skull_charm: { name: '해골 열쇠고리', grade: 'uncommon', value: 80, icon: 'skull', random: true,
      effect: { silverBoost: 0.25 }, desc: '은화 냄새를 잘 맡는 해골.' },
    glass_eye: { name: '유리 눈알', grade: 'rare', value: 150, icon: 'eye', random: true,
      effect: { crit: 0.1 }, desc: '약한 곳을 정확히 노려본다.' },
    bat_quill: { name: '박쥐 날개 깃펜', grade: 'rare', value: 150, icon: 'quill', random: true,
      effect: { iceBoost: 0.3 }, desc: '잉크가 늘 차갑다.' },
    hat_pin: { name: '마녀 모자 핀', grade: 'rare', value: 160, icon: 'pin', random: true,
      effect: { maxMp: 12, mpRegen: 1 }, desc: '모자에 꽂으면 머리가 맑아진다.' },
    moon_key: { name: '달의 열쇠', grade: 'legend', value: 400, icon: 'moonkey', random: true,
      effect: { atk: 5, maxHp: 20, maxMp: 10 }, desc: '어느 문을 여는 열쇠인지는 아무도 모른다.' },
  };
  // 층별 무작위 골동품 등급 확률(%) [일반, 고급, 희귀, 전설]
  const GRADE_ODDS = { 1: [70, 25, 5, 0], 2: [60, 30, 9, 1], 3: [45, 38, 15, 2], 4: [35, 40, 21, 4], 5: [25, 40, 28, 7] };

  // traits: charger(기 모으기) evasive(회피율) regen(턴당 회복%) curser(저주 확률) poisoner(독 확률) drain(흡혈 비율)
  const ENEMIES = {
    dustwisp: { name: '먼지 도깨비불', hp: 22, atk: 11, def: 1, exp: 6, silver: [2, 5], weak: 'fire',
      traits: {}, drops: [['hp_potion', 0.08]], desc: '창고 먼지가 뭉쳐 생긴 도깨비불. 재채기를 부른다.' },
    teacup: { name: '이 빠진 찻잔', hp: 29, atk: 12, def: 3, exp: 7, silver: [3, 5], weak: 'ice',
      traits: {}, drops: [['hp_potion', 0.1]], desc: '식은 차를 엎지르며 달려든다.' },
    waxslime: { name: '촛농 슬라임', hp: 31, atk: 11, def: 2, exp: 8, silver: [3, 6], weak: 'ice', resist: 'fire',
      traits: { regen: 0.06 }, drops: [['lamp_oil', 0.15]], desc: '불을 먹고 자란다. 불은 잘 안 듣는다.' },
    giggledoll: { name: '깔깔 인형', hp: 41, atk: 14, def: 3, exp: 12, silver: [4, 7], weak: 'fire',
      traits: { charger: true }, drops: [['firecracker', 0.12]], desc: '웃음을 모았다가 한꺼번에 터뜨린다.' },
    mirrorbat: { name: '거울 박쥐', hp: 34, atk: 15, def: 2, exp: 12, silver: [4, 7], weak: 'ice',
      traits: { evasive: 0.3 }, drops: [['dew', 0.12]], desc: '날개가 거울이라 맞히기 어렵다.' },
    shroomella: { name: '독버섯 우산', hp: 38, atk: 13, def: 4, exp: 13, silver: [5, 8], weak: 'fire',
      traits: { poisoner: 0.35 }, drops: [['herb', 0.25]], desc: '빙글 돌며 독 포자를 뿌린다.' },
    cursedframe: { name: '저주 액자', hp: 50, atk: 17, def: 5, exp: 18, silver: [6, 10], weak: 'light', resist: 'ice',
      traits: { curser: 0.3 }, drops: [['salt', 0.15]], desc: '그림 속 사람이 눈을 흘기면 힘이 빠진다.' },
    rustarmor: { name: '녹슨 갑옷', hp: 66, atk: 17, def: 10, exp: 20, silver: [7, 11], weak: 'ice',
      traits: {}, drops: [['key', 0.15]], desc: '속은 비었는데 무척 단단하다. 마법이 더 잘 든다.' },
    broomghost: { name: '빗자루 유령', hp: 46, atk: 18, def: 3, exp: 18, silver: [6, 10], weak: 'fire',
      traits: { evasive: 0.25 }, drops: [['feather', 0.12]], desc: '주인 잃은 빗자루가 쓸고 지나간다.' },
    shadowhand: { name: '그림자 손', hp: 60, atk: 21, def: 5, exp: 24, silver: [8, 12], weak: 'light',
      traits: { drain: 0.5 }, drops: [['mp_potion', 0.15]], desc: '닿는 것의 기운을 빨아들인다.' },
    skelibrarian: { name: '해골 사서', hp: 62, atk: 20, def: 6, exp: 25, silver: [8, 13], weak: 'fire',
      traits: { curser: 0.3 }, drops: [['sand', 0.3]], desc: '조용히 하라며 저주 도장을 찍는다.' },
    stuffedcrow: { name: '박제 까마귀', hp: 53, atk: 22, def: 4, exp: 24, silver: [8, 12], weak: 'ice',
      traits: { evasive: 0.3 }, drops: [['sand', 0.25], ['feather', 0.1]], desc: '유리 눈이 반짝이면 부리가 날아온다.' },
    lockmimic: { name: '자물쇠 미믹', hp: 79, atk: 24, def: 9, exp: 32, silver: [12, 20], weak: 'ice',
      traits: { charger: true }, drops: [['key', 0.3]], antiqueDrop: 0.25, desc: '상자인 척하다가 덥석 문다.' },
    sealcandle: { name: '봉인 촛불', hp: 62, atk: 22, def: 5, exp: 30, silver: [10, 15], weak: 'ice', resist: 'fire',
      traits: { regen: 0.08 }, drops: [['lamp_oil', 0.2], ['mp_potion', 0.15]], desc: '봉인을 지키는 꺼지지 않는 촛불.' },

    mirrorbat_king: { name: '거울 박쥐 대장', hp: 90, atk: 15, def: 3, exp: 40, silver: [30, 30], weak: 'ice',
      traits: { evasive: 0.35, drain: 0.5 }, elite: true, noFlee: true, scale: 1.25,
      desc: '세라의 거울 속 그림자를 붙잡고 있는 박쥐들의 대장.' },
    director: { name: '깔깔 극장장', hp: 240, atk: 20, def: 5, exp: 70, silver: [60, 60], weak: 'ice',
      traits: {}, boss: true, noFlee: true, scale: 1.3, script: ['attack', 'curse', 'charge'], curtainCall: true,
      desc: '무너진 인형극 무대의 주인. 웃음을 퍼뜨린다.' },
    lockmimic_king: { name: '황금 자물쇠 대장', hp: 300, atk: 27, def: 10, exp: 80, silver: [80, 80], weak: 'ice',
      traits: { charger: true }, elite: true, noFlee: true, scale: 1.3, antiqueDrop: 1,
      desc: '달빛 제단을 지키는 미믹들의 대장.' },
    nocturne: { name: '그림자 집사 녹턴', hp: 520, atk: 27, def: 7, exp: 0, silver: [0, 0], weak: 'light',
      traits: {}, boss: true, noFlee: true, scale: 1.35,
      script: ['attack', 'curse', 'attack', 'charge'], script2: ['attack', 'charge', 'attack', 'curse'], shieldAt: 0.5,
      desc: '봉인 창고 가장 깊은 곳의 집사. 루미의 그림자 조각을 쥐고 있다.' },
  };

  const FLOORS = [
    null,
    { id: 1, name: '먼지 쌓인 창고', seed: 4127, recLv: 1, monsters: 4, chests: 2, events: 2, traps: 1,
      enemies: [['dustwisp', 4], ['teacup', 3], ['waxslime', 3]], fountain: true, door: false, key: true, locked: true,
      puzzle: false, merchant: false, markers: ['a'], down: true,
      palette: { floor: '#5b4b6e', floor2: '#625174', wall: '#1a1222', wallTop: '#2b2038', glow: '#c9a0ff' } },
    { id: 2, name: '울음소리 복도', seed: 9203, recLv: 2, monsters: 5, chests: 2, events: 3, traps: 2,
      enemies: [['teacup', 1], ['waxslime', 1], ['giggledoll', 3], ['mirrorbat', 3], ['shroomella', 3]],
      fountain: true, door: true, key: true, locked: false, puzzle: true, merchant: false, markers: ['b'], down: true,
      palette: { floor: '#4a5470', floor2: '#505b78', wall: '#141824', wallTop: '#222839', glow: '#9cc3ff' } },
    { id: 3, name: '거꾸로 교실', seed: 3301, recLv: 3, monsters: 6, chests: 2, events: 3, traps: 2,
      enemies: [['giggledoll', 1], ['cursedframe', 3], ['rustarmor', 3], ['broomghost', 3], ['shroomella', 1]],
      fountain: true, door: true, key: true, locked: false, puzzle: false, merchant: true, markers: ['c', 'e'], down: true,
      palette: { floor: '#6a5050', floor2: '#725757', wall: '#1d1415', wallTop: '#2f2223', glow: '#ffb38a' } },
    { id: 4, name: '빗자루 묘지', seed: 7741, recLv: 4, monsters: 6, chests: 3, events: 3, traps: 2,
      enemies: [['shadowhand', 3], ['skelibrarian', 3], ['stuffedcrow', 3], ['broomghost', 1], ['rustarmor', 1]],
      fountain: true, door: true, key: true, locked: true, puzzle: true, merchant: false, markers: ['d'], down: true,
      palette: { floor: '#48604f', floor2: '#4f6856', wall: '#121a15', wallTop: '#1f2b24', glow: '#9fe0bf' } },
    { id: 5, name: '자정의 봉인실', seed: 5519, recLv: 5, monsters: 6, chests: 2, events: 2, traps: 2,
      enemies: [['lockmimic', 2], ['sealcandle', 3], ['shadowhand', 2], ['skelibrarian', 2], ['stuffedcrow', 1]],
      fountain: true, door: true, key: true, locked: false, puzzle: false, merchant: true, markers: ['f'], down: false,
      boss: 'nocturne', mimic: 1,
      palette: { floor: '#4a4170', floor2: '#514778', wall: '#110d1e', wallTop: '#1c1730', glow: '#ffe680' } },
  ];

  const NPCS = {
    rumi: { name: '루미', role: '저주골동품부 1학년', kind: 'witch', hair: '#7b5bc4', eye: '#ffcf5a' },
    mukmul: { name: '먹물', role: '부실 고양이', kind: 'cat' },
    letter: { name: '모르가 선배의 편지', role: '', kind: 'letter' },
    council: { name: '학생회 공문', role: '', kind: 'letter' },
    kiki: { name: '끼끼 할멈', role: '박쥐네 매점 주인', kind: 'batgranny' },
    momo: { name: '모모 선생님', role: '양호 선생님', kind: 'mummy' },
    wanderer: { name: '방랑냥', role: '떠돌이 고양이 상인', kind: 'cat2' },
    portraits: { name: '수다쟁이 초상화 자매', role: '', kind: 'portraits' },
    popo: { name: '포포', role: '1학년 · 합창부', kind: 'student', hair: '#f4a3be', style: 1, eye: '#5a3b6e' },
    sera: { name: '세라', role: '2학년 · 연극부', kind: 'student', hair: '#efd77a', style: 2, eye: '#3f6db0' },
    danhobak: { name: '단호박', role: '2학년 · 조리부', kind: 'student', hair: '#ef8c3e', style: 3, eye: '#6b3a1f' },
    noeul: { name: '노을', role: '3학년 · 문예부', kind: 'student', hair: '#c4546e', style: 0, eye: '#4a2a35', glasses: true },
    hwiparam: { name: '휘파람', role: '2학년 · 비행부', kind: 'student', hair: '#72b6e6', style: 2, eye: '#1f4a6b' },
    kongal: { name: '콩알', role: '1학년 · 인형부', kind: 'student', hair: '#90d38b', style: 1, eye: '#2e5a2a' },
    tiktok: { name: '틱톡 조교', role: '교무실 조교', kind: 'student', hair: '#a59886', style: 0, eye: '#3a3a3a', glasses: true },
    belladonna: { name: '벨라도나', role: '학생회장', kind: 'student', hair: '#3a2b55', style: 3, eye: '#c0405a' },
    nocturne: { name: '녹턴', role: '그림자 집사', kind: 'enemy', enemy: 'nocturne' },
    director: { name: '깔깔 극장장', role: '', kind: 'enemy', enemy: 'director' },
  };

  // objective.type: fetch(특정 방에서 물건 찾기) defeat(특정 적 처치) items(재료 모으기) puzzle(이상한 방 해결)
  const QUESTS = [
    { id: 'q1', cursedName: '훌쩍이는 오르골', customer: 'popo', antique: 'musicbox', buy: 30, unlock: {},
      symptom: '밤마다 혼자 훌쩍이며 운다.',
      story: ['선배! 이 오르골 좀 사주세요…', '밤마다 혼자 훌쩍훌쩍 울어요. 기숙사 애들이 다 깼어요.', '태엽 하나가 빠진 뒤로 이래요.'],
      objective: { type: 'fetch', floor: 1, marker: 'a', item: 'q_spring', place: '먼지 쌓인 음악실 사물함' },
      hint: 'B1 어딘가의 「먼지 쌓인 음악실 사물함」에서 잃어버린 태엽을 찾자.',
      found: ['삐걱— 사물함을 열자 작은 태엽이 찌르륵 떨었다.', '잃어버린 태엽을 손에 넣었다!'],
      purify: '태엽을 끼우자 오르골이 마지막으로 크게 훌쩍이더니… 조용한 자장가를 연주하기 시작했다.' },
    { id: 'q2', cursedName: '따라오는 손거울', customer: 'sera', antique: 'handmirror', buy: 50, unlock: { floor: 2 },
      symptom: '거울 속 내가 한 박자 늦게 움직인다.',
      story: ['이 손거울, 제가 웃으면 거울 속 저는 한 박자 늦게 웃어요.', '어제는… 아예 안 웃었어요.', '거울 속 제가 어디론가 끌려가는 것 같아요.'],
      objective: { type: 'defeat', floor: 2, marker: 'b', enemy: 'mirrorbat_king', place: '깨진 거울의 막다른 길' },
      hint: 'B2 「깨진 거울의 막다른 길」에서 거울 박쥐 대장을 물리치자.',
      found: ['깨진 거울 조각 사이로 커다란 박쥐가 거꾸로 매달려 있다.', '그 날개에 세라의 그림자가 비친다!'],
      purify: '거울을 닦자 세라의 모습이 정확히 제 박자에 맞춰 손을 흔들었다.' },
    { id: 'q3', cursedName: '식지 않는 찻주전자', customer: 'danhobak', antique: 'teapot', buy: 40, unlock: { purified: 1 },
      symptom: '사흘째 저절로 끓고 있다.',
      story: ['찻주전자가 식질 않아요. 사흘째 펄펄 끓어요!', '조리실이 사우나가 됐어요. 쿠키가 다 녹았어요…', '뚜껑을 열면 "더 마셔" 하고 속삭여요.'],
      objective: { type: 'items', items: { salt: 1, dew: 1 }, place: '부실 정화대' },
      hint: '정화 소금 1개와 달빛 이슬 1개를 모아 부실에서 정화하자. (매점·봉인 창고)',
      purify: '달빛 이슬을 한 방울 떨어뜨리자, 찻주전자가 "후우—" 하고 긴 한숨을 쉬며 식었다.' },
    { id: 'q4', cursedName: '글자가 기어다니는 일기장', customer: 'noeul', antique: 'diary', buy: 60, unlock: { floor: 3 },
      symptom: '글자가 밤마다 다른 페이지로 이사 간다.',
      story: ['일기장 글자들이 밤마다 다른 페이지로 이사를 가요.', '어젯밤 쓴 일기가 오늘 아침엔 시간표 위에 있었어요.', '봉인 창고의 「거꾸로 교실」에서 이 일기장을 주웠어요. 거기가 원래 집인가 봐요.'],
      objective: { type: 'puzzle', floor: 3, marker: 'c', place: '거꾸로 교실' },
      hint: 'B3 「거꾸로 교실」에 들어가 꺼진 촛불을 모두 밝히자.',
      found: ['천장에 책상이 매달린 교실. 꺼진 촛불들이 일렬로 서 있다.', '"모두 밝히면 글자들이 집으로 돌아갈 거야."'],
      purify: '일기장을 펼치자 흩어졌던 글자들이 줄을 맞춰 제 페이지로 돌아갔다.' },
    { id: 'q5', cursedName: '삐걱대는 마녀 빗자루', customer: 'hwiparam', antique: 'broom', buy: 80, unlock: { floor: 4 },
      symptom: '주인을 태우고 지하로 내려가려 한다.',
      story: ['제 빗자루가 저를 태우고 자꾸 지하로 내려가려 해요!', '어제는 봉인 창고 B2까지 갔다 왔어요. 무서웠어요.', '빗자루 묘지에 가면 얘를 얌전하게 할 끈이 있대요.'],
      objective: { type: 'fetch', floor: 4, marker: 'd', item: 'q_strap', place: '빗자루 묘지 관리인 오두막' },
      hint: 'B4 「빗자루 묘지 관리인 오두막」에서 빗자루 끈을 찾자.',
      found: ['오두막 벽에 낡은 가죽 끈이 걸려 있다.', '빗자루 끈을 손에 넣었다!'],
      purify: '끈을 묶자 빗자루가 부르르 떨더니, 얌전히 휘파람의 손에 안겼다.' },
    { id: 'q6', cursedName: '웃음이 멈추지 않는 인형', customer: 'kongal', antique: 'doll', buy: 70, unlock: { floor: 3 },
      symptom: '계속 깔깔 웃는다. 주인도 따라 웃게 된다.',
      story: ['인형이 계속 깔깔 웃어요. 깔깔.', '저도 따라 웃게 돼요… 무서운데… 깔깔.', '웃음소리가 봉인 창고 쪽 무대에서 들려온대요.'],
      objective: { type: 'defeat', floor: 3, marker: 'e', enemy: 'director', place: '무너진 인형극 무대' },
      hint: 'B3 「무너진 인형극 무대」의 깔깔 극장장을 쓰러뜨리자.',
      found: ['찢어진 커튼 뒤에서 커다란 인형이 고개를 꺾는다.', '"관객이 왔군! 웃어라, 웃어라!"'],
      purify: '인형의 입꼬리가 천천히 내려와, 잔잔한 미소로 멈췄다.' },
    { id: 'q7', cursedName: '얼어붙은 회중시계', customer: 'tiktok', antique: 'watch', buy: 100, unlock: { floor: 4 },
      symptom: '본 사람마다 3초씩 멈춘다.',
      story: ['이 회중시계를 본 사람은 3초씩 멈춥니다.', '교무회의가 세 시간째 3초씩 멈추고 있어요.', '…지금 제가 멈췄었나요?'],
      objective: { type: 'items', items: { sand: 2, salt: 1 }, place: '부실 정화대' },
      hint: '시간의 모래 2개와 정화 소금 1개를 모아 부실에서 정화하자. (B4·매점)',
      purify: '시간의 모래를 흘려 넣자 멈췄던 초침이 째깍, 하고 다시 걷기 시작했다.' },
    { id: 'q8', cursedName: '달을 삼킨 브로치', customer: 'belladonna', antique: 'brooch', buy: 150, unlock: { floor: 5 },
      symptom: '빛을 먹어 학생회실이 늘 밤이다.',
      story: ['…학생회실이 늘 밤이야. 이 브로치가 빛을 먹거든.', '너희 부가 정말 정화를 한다면, 증명해 봐.', '브로치가 삼킨 달빛은 봉인 창고 맨 아래 제단에 묶여 있다더군.'],
      objective: { type: 'defeat', floor: 5, marker: 'f', enemy: 'lockmimic_king', place: '달빛 제단' },
      hint: 'B5 「달빛 제단」을 지키는 황금 자물쇠 대장을 쓰러뜨리자.',
      found: ['제단 위 황금 상자가 철컥, 철컥 이빨을 부딪친다.', '상자 틈으로 달빛이 새어 나온다!'],
      purify: '브로치가 달빛을 되찾자, 부실 창문 너머로 학생회실 불이 환하게 켜졌다.' },
  ];

  const BADGES = [
    { id: 'first_buy', name: '첫 매입', desc: '처음으로 저주 물건을 매입했다.', reward: 20 },
    { id: 'first_purify', name: '첫 정화', desc: '처음으로 저주를 정화했다.', reward: 30 },
    { id: 'purify5', name: '폐부 위기 탈출', desc: '정화 실적 5건을 달성했다.', reward: 100 },
    { id: 'floor3', name: '중층 탐험가', desc: '봉인 창고 B3에 도달했다.', reward: 30 },
    { id: 'floor5', name: '심층 탐험가', desc: '봉인 창고 B5에 도달했다.', reward: 50 },
    { id: 'director', name: '커튼콜', desc: '깔깔 극장장을 쓰러뜨렸다.', reward: 50 },
    { id: 'nocturne', name: '자정의 승리', desc: '그림자 집사 녹턴을 쓰러뜨렸다.', reward: 100 },
    { id: 'quiz5', name: '초상화 단골', desc: '초상화 퀴즈를 5번 맞혔다.', reward: 30 },
    { id: 'gamble5', name: '항아리 친구', desc: '운명의 항아리에 5번 은화를 넣었다.', reward: 20 },
    { id: 'shop10', name: '매점 VIP', desc: '매점에서 10번 물건을 샀다.', reward: 20 },
    { id: 'codex8', name: '수집가', desc: '골동품 도감 8종을 채웠다.', reward: 50 },
    { id: 'legend', name: '전설의 감정사', desc: '전설 등급 골동품을 정화했다.', reward: 50 },
    { id: 'weak20', name: '약점 공략가', desc: '약점 공격을 20번 성공했다.', reward: 30 },
    { id: 'puzzle3', name: '촛불지기', desc: '이상한 방을 3번 해결했다.', reward: 30 },
    { id: 'level5', name: '어엿한 견습 마녀', desc: '레벨 5에 도달했다.', reward: 30 },
  ];

  const QUIZ = [
    { q: '양호실 치료비는 얼마일까?', a: ['10은화', '20은화', '50은화'], c: 1 },
    { q: '기를 모으는 적을 확실히 멈추는 마법은?', a: ['불씨', '얼음 가시', '치유'], c: 1 },
    { q: '정화 소금으로 풀 수 있는 상태는?', a: ['독', '저주', '잠'], c: 1 },
    { q: '먹물이 제일 좋아하는 간식은?', a: ['멸치 쿠키', '딸기 우유', '달빛 젤리'], c: 0 },
    { q: '골동품 등급 중 가장 높은 것은?', a: ['희귀', '전설', '고급'], c: 1 },
    { q: '촛농 슬라임에게 잘 안 듣는 마법은?', a: ['불씨', '얼음 가시', '정화의 빛'], c: 0 },
    { q: '공간이동 항아리는 어디로 보내줄까?', a: ['가본 적 있는 층', '아무 층이나', '학교 옥상'], c: 0 },
    { q: '해독 허브는 무엇을 치료할까?', a: ['저주', '독', '화상'], c: 1 },
    { q: '저주골동품부가 하는 일은?', a: ['저주 물건을 판다', '저주 물건을 사서 정화한다', '저주를 건다'], c: 1 },
    { q: '모르가 선배의 편지에 따르면 먹물 밥은 하루 몇 번?', a: ['한 번', '두 번', '세 번'], c: 1 },
    { q: '마력을 채워주는 물약의 색은?', a: ['빨강', '파랑', '초록'], c: 1 },
    { q: '도망칠 수 없는 상대는?', a: ['보스', '거울 박쥐', '찻잔'], c: 0 },
    { q: '등불 기름을 쓰면 어떻게 될까?', a: ['시야가 넓어진다', '체력이 오른다', '문이 열린다'], c: 0 },
    { q: '녹슨 갑옷에게 더 잘 드는 공격은?', a: ['물리 공격', '마법', '둘 다 같다'], c: 1 },
    { q: '귀환 깃털을 쓰면 어디로 갈까?', a: ['한 층 위', '학교', '보스 방'], c: 1 },
  ];

  const LINES = {
    intro: [
      { who: null, text: '마녀학교 지하에는 「봉인 창고」가 있다. 오래된 저주 물건들이 잠든 곳.' },
      { who: null, text: '그리고 그 바로 위에는… 아무도 찾지 않는 동아리방이 하나 있다.' },
      { who: 'rumi', text: '저주골동품부… 여기 맞지? 모르가 선배님, 계세요?' },
      { who: 'mukmul', text: '냐아.' },
      { who: null, text: '책상 위에 편지와 공문이 놓여 있다.' },
      { who: 'letter', text: '루미에게. 갑자기 떠나게 됐어. 부실을 부탁해. 손님이 저주 물건을 가져오면 사들이고, 정화해서 되팔면 돼.' },
      { who: 'letter', text: '봉인 창고는… 어차피 들어가겠지. 조심해. 아, 먹물 밥은 하루 두 번! 간식은 멸치 쿠키.' },
      { who: 'council', text: '[학생회 공문] 저주골동품부는 실적 부진으로 학기말 폐부 예정. 단, 정화 실적 5건을 달성하면 존속을 허가함.' },
      { who: 'rumi', text: '폐부라니! …그런데 내 그림자는 오늘따라 왜 안 보이지?' },
      { who: 'mukmul', text: '냐. (먹물이 바닥을 긁는다. 그림자 냄새가 봉인 창고 아래에서 난다는 듯이.)' },
      { who: 'rumi', text: '좋아. 일단 손님부터 받아보자!' },
    ],
    bossIntro: [
      { who: 'nocturne', text: '어서 오십시오, 그림자 없는 아가씨.' },
      { who: 'nocturne', text: '찾으시는 물건은… 이것이군요. (녹턴의 손끝에 루미의 그림자 조각이 흔들린다)' },
      { who: 'rumi', text: '내 그림자! 돌려줘!' },
    ],
    bossWin: [
      { who: 'nocturne', text: '오늘은… 여기까지 해두지요. 봉인은 아직 많이 남았으니까요.' },
      { who: null, text: '그림자 조각을 되찾았다! 루미의 발끝에 작은 그림자가 돌아왔다.' },
    ],
    ending: [
      { who: 'council', text: '[학생회 공문] 정화 실적 5건 확인. 저주골동품부의 존속을 허가함.' },
      { who: 'rumi', text: '해냈다! 먹물, 우리 부실 안 없어진대!' },
      { who: 'mukmul', text: '냐아아~' },
      { who: 'rumi', text: '그림자는 아직 발끝까지만 돌아왔지만… 봉인 창고 아래에 나머지가 있겠지.' },
      { who: null, text: '— 프로토타입은 여기까지. 이후에도 자유롭게 탐험·매입·수집을 계속할 수 있다. —' },
    ],
    mukmulTips: [
      '냐. (손님 물건을 매입하면 의뢰가 시작된다는 표정이다)',
      '냐아. (봉인 창고에서 막히면 날 불러. 냄새로 길을 찾아줄게)',
      '냥. (기를 모으는 적에게는 얼음 가시가 최고야)',
      '냐…? (약점을 맞히면 적 이름 옆에 약점이 기록된다)',
      '냐앙. (정화한 골동품은 팔아도 되고, 장착해서 써도 돼)',
      '냐. (체력이 부족하면 양호실. 모모 선생님은 20은화)',
      '냥냥. (같은 층이라도 다시 들어가면 상자가 새로 채워져)',
    ],
    kiki: ['끼끼끼, 어서 와. 박쥐네 매점이야.', '물약은 넉넉히 사 둬. 봉인 창고는 배고픈 곳이거든.', '은화가 모자라? 끼끼, 외상은 없어.', '정화 소금은 늘 잘 팔리지.', '끼… 저주 냄새가 나는구나. 또 깊이 내려갔지?'],
    momo: ['붕대 많이 있어요. 어디 다쳤어요?', '무리하면 안 돼요. 먹물이 걱정해요.', '독은 해독 허브로도 나아요. 그래도 여기 오면 더 확실해요.'],
    wanderer: ['냥. 비싸지만 급하잖아?', '봉인 창고에선 내가 유일한 가게다냥.', '은화만 있으면 뭐든 판다냥. 거의.'],
    rumors: [
      '계단은 언제나 입구에서 가장 먼 곳에 있다더라.',
      '얼음 가시는 기를 모으는 녀석을 멈춰. — 선배',
      '먹물한테 물어봐. 코가 제일 좋으니까.',
      '저주 액자는 빛을 싫어해.',
      '잠긴 문 뒤엔 꼭 좋은 게 있지.',
      '녹슨 갑옷은 단단해. 마법을 써.',
      '정화 소금은 저주 상태를 풀어준다.',
    ],
  };

  W.DATA = {
    GRADES, GRADE_ORDER, ELEMENTS, PLAYER, EXP_CURVE, SPELLS, SPELL_ORDER, ITEMS, SHOP_TABS,
    ANTIQUES, GRADE_ODDS, ENEMIES, FLOORS, NPCS, QUESTS, BADGES, QUIZ, LINES,
    TUNING: {
      encounterRate: 0.04, encounterGrace: 3, startSafeRadius: 2,
      fleeBase: 0.6, critBase: 0.08, critMult: 1.6, chargeMult: 2.3, bossChargeMult: 2.5,
      petBase: 0.12, curseMult: 0.7, curseTurns: 3, poisonTicks: 6, poisonPct: 0.05, poisonStepEvery: 3,
      burnChance: 0.25, burnTurns: 3, freezeChance: 0.4, shieldMult: 0.4, shieldTurns: 3,
      infirmaryCost: 20, sellRatio: 0.5, defeatSilverLoss: 0.3, petHints: 3, sightBase: 3,
      chestAntiqueChance: { 1: 0.25, 2: 0.3, 3: 0.35, 4: 0.4, 5: 0.45 },
      gambleCost: 20,
    },
  };
})();
